# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = false
linemode = "size"
show_hidden = true

[preview]
image_quality = 50

[opener]
view = [
#	{ run = "less %s", desc = "$PAGER", for = "unix", block = true },
	{ run = '$PAGER "$@"', desc = "$PAGER", for = "unix", block = true },
]

[open]
rules = [
	# Folder
	{ url = "*/", use = [ "view", "edit", "open", "reveal" ] },
	# Text
	{ mime = "text/*", use = [ "view", "edit", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "view", "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "view", "edit", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "view", "edit", "reveal" ] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download" },
	# Fallback
	{ url = "*", use = [ "open", "reveal" ] },
]

[tasks]
image_alloc = 0
image_bound = [0, 0]

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
