# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$docker_context\
$conda\
$package\
$os\
$container\
$username\
$hostname\
$line_break\
$character"""

right_format = """
$cmd_duration\
$status\
$jobs\
$shlvl\
$time"""

# Inserts a blank line between shell prompts
add_newline = true

# Sets which color palette from palettes to use
palette = 'catppuccin_macchiato'


## Left Prompt

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold lavender)"
vimcmd_replace_one_symbol = "[<](bold lavender)"

[fill]
disabled = false
symbol = ' '

[directory]
style = "peach"
truncation_length = 0
truncate_to_repo = false
read_only = ' ro'
read_only_style = 'red'
truncation_symbol = ".../"
repo_root_style = "bold peach"

[git_branch]
symbol = "git "
style = "yellow"
format = '[$symbol$branch(:$remote_branch)]($style) '
truncation_symbol = "..."

[git_status]
style = "yellow"
ahead = ">${count}"
behind = "<${count}"
diverged = "<>"
renamed = "r"
deleted = "x"

[c]
symbol = "C "
style = "green"
format = '[$symbol($version )]($style)'

[cpp]
symbol = "C++ "
style = "green"
format = '[$symbol($version )]($style)'

[cmake]
symbol = "cmake "
style = "green"
format = '[$symbol($version )]($style)'

[cobol]
symbol = "cobol "
style = "green"
format = '[$symbol($version )]($style)'

[crystal]
symbol = "cr "
style = "green"
format = '[$symbol($version )]($style)'

[daml]
symbol = "daml "
style = "green"
format = '[$symbol($version )]($style)'

[dart]
symbol = "dart "
style = "green"
format = '[$symbol($version )]($style)'

[deno]
symbol = "deno "
style = "green"
format = '[$symbol($version )]($style)'

[dotnet]
symbol = ".NET "
style = "green"
format = '[$symbol($version )(target $tfm )]($style)'

[elixir]
symbol = "exs "
style = "green"
format = '[$symbol($version )]($style)'

[elm]
symbol = "elm "
style = "green"
format = '[$symbol($version )]($style)'

[erlang]
symbol = "erl "
style = "green"
format = '[$symbol($version )]($style)'

[fennel]
symbol = "fnl "
style = "green"
format = '[$symbol($version )]($style)'

[fortran]
symbol = "fortran "
style = "green"
format = '[$symbol($version )]($style)'

[gleam]
symbol = "gleam "
style = "green"
format = '[$symbol($version )]($style)'

[golang]
symbol = "go "
style = "green"
format = '[$symbol($version )]($style)'

[guix_shell]
symbol = "guix "
style = "green"
format = '[$symbol($version )]($style)'

[haskell]
symbol = "haskell "
style = "green"
format = '[$symbol($version )]($style)'

[haxe]
symbol = "hx "
style = "green"
format = '[$symbol($version )]($style)'

[helm]
symbol = "helm "
style = "green"
format = '[$symbol($version )]($style)'

[java]
symbol = "java "
style = "green"
format = '[$symbol($version )]($style)'

[julia]
symbol = "jl "
style = "green"
format = '[$symbol($version )]($style)'

[kotlin]
symbol = "kt "
style = "green"
format = '[$symbol($version )]($style)'

[gradle]
symbol = "gradle "
style = "green"
format = '[$symbol($version )]($style)'

[lua]
symbol = "lua "
style = "green"
format = '[$symbol($version )]($style)'

[nim]
symbol = "nim "
style = "green"
format = '[$symbol($version )]($style)'

[nodejs]
symbol = "nodejs "
style = "green"
format = '[$symbol($version )]($style)'

[ocaml]
symbol = "ml "
style = "green"
format = '[$symbol($version )]($style)'

[opa]
symbol = "opa "
style = "green"
format = '[$symbol($version )]($style)'

[perl]
symbol = "pl "
style = "green"
format = '[$symbol($version )]($style)'

[php]
symbol = "php "
style = "green"
format = '[$symbol($version )]($style)'

[pulumi]
symbol = "pulumi "
style = "green"
format = '[$symbol($version )]($style)'

[purescript]
symbol = "purs "
style = "green"
format = '[$symbol($version )]($style)'

[python]
symbol = "py "
style = "green"
format = '[$symbol($version )]($style)'

[quarto]
symbol = "quarto "
style = "green"
format = '[$symbol($version )]($style)'

[raku]
symbol = "raku "
style = "green"
format = '[$symbol($version )]($style)'

[rlang]
symbol = "r "
style = "green"
format = '[$symbol($version )]($style)'

[red]
symbol = "red "
style = "green"
format = '[$symbol($version )]($style)'

[ruby]
symbol = "rb "
style = "green"
format = '[$symbol($version )]($style)'

[rust]
symbol = "rs "
style = "green"
format = '[$symbol($version )]($style)'

[scala]
symbol = "scala "
style = "green"
format = '[$symbol($version )]($style)'

[solidity]
symbol = "solidity "
style = "green"
format = '[$symbol($version )]($style)'

[swift]
symbol = "swift "
style = "green"
format = '[$symbol($version )]($style)'

[terraform]
symbol = "terraform "
style = "green"
format = '[$symbol($version )]($style)'

[typst]
symbol = "typst "
style = "green"
format = '[$symbol($version )]($style)'

[vagrant]
symbol = "vagrant "
style = "green"
format = '[$symbol($version )]($style)'

[zig]
symbol = "zig "
style = "green"
format = '[$symbol($version )]($style)'

[docker_context]
symbol = "docker "
style = "sapphire"
format = '[$symbol$context]($style) '

[conda]
symbol = "conda "
style = "sapphire"
format = '[$symbol$environment]($style) '
ignore_base = false

[package]
symbol = "pkg "
style = "sapphire"
format = '[$symbol$version]($style) '

[os]
disabled = false
style = "sapphire"

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
AOSC = "aosc "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[container]
symbol = "container "
style = "sapphire"

[username]
style_root = "red"
style_user = "lavender"
format = '[$user]($style)'
show_always = true

[hostname]
style = "lavender"
format = '[@$hostname ]($style)'
ssh_only = false

[line_break]
disabled = false


## Right Prompt

[cmd_duration]
style = "lavender"
format = "in $duration "
show_milliseconds = true

[status]
disabled = false
symbol = "x"
not_executable_symbol = "noexec"
not_found_symbol = "notfound"
sigint_symbol = "sigint"
signal_symbol = "sig"
format = '[$symbol $status $common_meaning$signal_name$maybe_int]($style) '

[jobs]
symbol = "jobs "
number_threshold = 1

[shlvl]
disabled = false
symbol = "shlvl "
threshold = 3

[time]
disabled = false
style = "lavender"
format = '[\[$time\]]($style)'
time_format = "%T"


## unuse

[buf]
symbol = "buf "

[nix_shell]
symbol = "nix "

[meson]
symbol = "meson "
truncation_symbol = "..."

[spack]
symbol = "spack "

[aws]
symbol = "aws "

[azure]
symbol = "az "

[bun]
symbol = "bun "

[fossil_branch]
symbol = "fossil "
truncation_symbol = "..."

[gcloud]
symbol = "gcp "

[hg_branch]
symbol = "hg "
truncation_symbol = "..."

[kubernetes]
symbol = "kubernetes "

[memory_usage]
symbol = "memory "

[mojo]
symbol = "mojo "

[nats]
symbol = "nats "

[netns]
symbol = "netns "

[odin]
symbol = "odin "

[openstack]
symbol = "openstack "

[pijul_channel]
symbol = "pijul "
truncation_symbol = "..."

[pixi]
symbol = "pixi "

[sudo]
symbol = "sudo "

[xmake]
symbol = "xmake "


## Palettes

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
